### PR TITLE
Add readme link to updated fork

### PR DESCRIPTION
**Pull request by NicoHood**
Just want to let you know (if you have missed it), that there is a fork of your project with a lot of improvements.
We gave you credit in the readme. Feel free to merge this PR as people will see it better then.

We are also working on even more bugfixes and improvements. Feel free to have a look:
https://github.com/nims11/IPod-Shuffle-4g/pull/25

Happy coding!

### CODE REVIEW

**Comment by NicoHood** [comment]
As discussed [here](https://github.com/NicoHood/IPod-Shuffle-4g/commit/8415d11b7edf0033958f91b9f95a4278ea26e943#commitcomment-16773973) would it be okay to change the license to MIT or should we use GPL?

**Comment by NicoHood** [comment]
Hi,
I've seen that you are still active on this repository. You possibly want to checkout our fork, as it has tons of new features now. You are welcome to review it :)

**Comment by ikelos** [comment]
Hi, sorry I did completely miss this.  The repo is set to watch, but not watch everything, so mentioning my name should be enough.  I'll give this a look in the next couple of days...  5:)

**Comment by ikelos** [comment]
Can you let me know what the MIT license offers that the GPL-2 licensed version would not?  As far as I can see it only lets people produce their own version without releasing the source back out?  I'm not necessarily against it, but it just seems to be easing restrictions designed to encourage sharing of code.  I'd like a good reason to change it before I do...

**Comment by NicoHood** [comment]
Yeah thats basically it. Its "do whatever with this software, but i am not responsible if it will detroy your pc".

I normally use MIT as it has no problems with other licences. I just missed that you originally used GPL, so that is all okay.

**Comment by ikelos** [comment]
Thanks, I thought I was going to have to review all the changes for all the versions you guys have developed, but it was just a readme change!  5:P  I've pushed a separate commit in my own words instead that should achieve the same effect, and explains a little about why this repo is so out of date.  Thanks for all your efforts!  5:)

**Comment by NicoHood** [comment]
Thanks! :)
If you ever have a new idea about the script, let us know, so we do not spend time on both projects which actually have the same functionallity then (like the pyhon3 conversion I realized after I updated it myself).

**Comment by ikelos** [comment]
Sure, sorry about the python3 conversion.  I changed my default interpreter a couple of weeks ago, which broke my code, so I fixed it.  As I mentioned in the readme, the code was a personal project, so it only sees activity when it doesn't work for me any more.  It has pretty much all of the features I care about, but I'll try to give you a heads-up if it ever breaks for me again.  5;P  I published the code more so that people who had time and interest to improve it could do so, which I'm grateful that you've done!  5:)

**Pull request closed without merging**
